// Zoho Leads-module picklist values pulled directly from Cornerstone's
// Zoho org via getFields. Keep these in sync if Zoho admin changes the
// picklist — values must match exactly or Zoho silently drops the field.

// Zoho field: Lead_Status (label "Interaction Status").
export const LEAD_STATUS_PICKLIST: string[] = [
  ">5 Outreach Attempts Made, No Contact",
  "Client Care Call/HR/Admin",
  "Contacted",
  "DUI - Service Not Offered",
  "Hang Up",
  "Junk Lead",
  "Lost Lead",
  "Not Contacted",
  "Potential: Still Assessing/Info Missing",
  "Pre Qualified",
  "Qualified Lead: Moving to Pipeline",
  "Contact in Future",
  "Requested No Further Contact",
  "Attempted to Contact",
  "Not Qualified",
];

// Zoho field: Lead_Score_Rating.
export const LEAD_SCORE_RATING_PICKLIST: string[] = [
  "⭐ Has no substance issue at all",
  "⭐⭐ Has substance abuse but little intention of entering treatment",
  "⭐⭐⭐ Mentions substance abuse but unable to pay or isn't within proximity",
  "⭐⭐⭐⭐ Has substance and intention to seek help but there are clear objections",
  "⭐⭐⭐⭐⭐ Ideal Candidate - Has substance abuse and is seeking help",
  "Unable To Score/Never Made Contact",
];

// Zoho field: CTM_Score (1-5 rating used for per-call manual rating).
export const CTM_SCORE_PICKLIST: string[] = ["1", "2", "3", "4", "5"];

// Zoho field: Level_of_Care_Requested. The Cornerstone "program interest"
// concept maps directly to this Zoho picklist. Values must match exactly.
export const LEVEL_OF_CARE_PICKLIST: string[] = [
  "BHRF",
  "PHP",
  "IOP5",
  "IOP3",
  "VIOP",
  "VIOP Adolescent",
  "VOP",
  "VOP Adult",
  "VOP Adolescent",
  "OP",
  "Detox",
  "DUI",
  "DV",
];

// Zoho field: Insurance_Type. Top-level insurance category.
export const INSURANCE_TYPE_PICKLIST: string[] = [
  "AHCCCS",
  "Cash Pay",
  "Private Insurance",
  "EPO",
  "HMO",
  "Medicare",
  "No Insurance",
  "Out of State Medicaid",
  "POS",
  "Unknown",
];

// Combined "Insurance Provider" picklist — AHCCCS providers from the
// AHCCCS_Insurance_Provider field PLUS Private_Insurance_Company values.
// zoho-writeback inspects the chosen value and routes it to the correct
// Zoho field based on whether it matches an AHCCCS provider name.
export const INSURANCE_PROVIDER_PICKLIST: string[] = [
  // AHCCCS providers (Arizona Medicaid plans)
  "AIHP",
  "AZ Complete",
  "Banner",
  "Care 1st",
  "Health Choice",
  "Humana AHCCCS",
  "Mercy Care",
  "Molina",
  "State BHS",
  "UHC AHCCCS",
  // Private insurance companies
  "Aetna",
  "Ambetter",
  "AmeriHealth",
  "Anthem",
  "Anthem Blue Cross",
  "BCBS",
  "BCBS AK (Premera Blue Cross Blue Shield of Alaska)",
  "BCBS AL (Blue Cross and Blue Shield of Alabama)",
  "BCBS AR (Arkansas Blue Cross and Blue Shield)",
  "BCBS AZ (Blue Cross Blue Shield of Arizona)",
  "BCBS CA (Blue Shield of California & Anthem Blue Cross)",
  "BCBS CO (Anthem Blue Cross Blue Shield of Colorado)",
  "BCBS CT (Anthem Blue Cross and Blue Shield of Connecticut)",
  "BCBS DC (CareFirst BlueCross BlueShield)",
  "BCBS DE (Highmark Blue Cross Blue Shield Delaware)",
  "BCBS FL (Florida Blue)",
  "BCBS GA (Anthem Blue Cross and Blue Shield of Georgia)",
  "BCBS HI (HMSA - Hawaii Medical Service Association)",
  "BCBS IA (Wellmark Blue Cross and Blue Shield of Iowa)",
  "BCBS ID (Blue Cross of Idaho)",
  "BCBS IL (Blue Cross and Blue Shield of Illinois)",
  "BCBS IN (Anthem Blue Cross and Blue Shield of Indiana)",
  "BCBS KS (Blue Cross and Blue Shield of Kansas)",
  "BCBS KY (Anthem Blue Cross and Blue Shield of Kentucky)",
  "BCBS LA (Blue Cross and Blue Shield of Louisiana)",
  "BCBS MA (Blue Cross Blue Shield of Massachusetts)",
  "BCBS MD (CareFirst BlueCross BlueShield of Maryland)",
  "BCBS ME (Anthem Blue Cross and Blue Shield of Maine)",
  "BCBS MI (Blue Cross Blue Shield of Michigan)",
  "BCBS MN (Blue Cross and Blue Shield of Minnesota)",
  "BCBS MO (Anthem Blue Cross and Blue Shield of Missouri)",
  "BCBS MS (Blue Cross & Blue Shield of Mississippi)",
  "BCBS MT (Blue Cross and Blue Shield of Montana)",
  "BCBS NC (Blue Cross and Blue Shield of North Carolina)",
  "BCBS ND (Blue Cross Blue Shield of North Dakota)",
  "BCBS NE (Blue Cross and Blue Shield of Nebraska)",
  "BCBS NH (Anthem Blue Cross and Blue Shield of New Hampshire)",
  "BCBS NJ (Horizon Blue Cross Blue Shield of New Jersey)",
  "BCBS NM (Blue Cross and Blue Shield of New Mexico)",
  "BCBS NV (Anthem Blue Cross and Blue Shield of Nevada)",
  "BCBS NY (Empire BlueCross BlueShield / Excellus BCBS / others by region)",
  "BCBS OH (Anthem Blue Cross and Blue Shield of Ohio)",
  "BCBS OK (Blue Cross and Blue Shield of Oklahoma)",
  "BCBS OR (Regence BlueCross BlueShield of Oregon)",
  "BCBS PA (Highmark / Independence Blue Cross depending on region)",
  "BCBS RI (Blue Cross & Blue Shield of Rhode Island)",
  "BCBS SC (BlueCross BlueShield of South Carolina)",
  "BCBS SD (Wellmark Blue Cross and Blue Shield of South Dakota)",
  "BCBS TN (BlueCross BlueShield of Tennessee)",
  "BCBS TX (Blue Cross and Blue Shield of Texas)",
  "BCBS UT (Regence BlueCross BlueShield of Utah)",
  "BCBS VA (Anthem Blue Cross and Blue Shield of Virginia)",
  "BCBS VT (Blue Cross and Blue Shield of Vermont)",
  "BCBS WA (Premera Blue Cross / Regence BlueShield of Washington)",
  "BCBS WI (Anthem Blue Cross and Blue Shield of Wisconsin)",
  "BCBS WV (Highmark Blue Cross Blue Shield West Virginia)",
  "BCBS WY (Blue Cross Blue Shield of Wyoming)",
  "Beacon Health Options",
  "Blue Cross Blue Shield (BCBS)",
  "Blue Shield of California",
  "Centene Corporation",
  "CHAMPVA (Civilian Health and Medical Program of the Department of Veterans Affairs)",
  "Cigna",
  "EBMS",
  "First Health",
  "GEHA",
  "Health Net",
  "Humana",
  "Kaiser Permanente",
  "Magellan",
  "Medicaid",
  "Medicaid: AIHP",
  "Medicaid: AZ Complete",
  "Medicaid: Banner",
  "Medicaid: Health Choice",
  "Medicaid: State-only BHS",
  "Medicaid: UHC Community",
  "Medicare",
  "Molina Healthcare",
  "Optum",
  "Other",
  "Tricare",
  "Triwest",
  "UHC",
  "UMR",
  "Western Health Advantage",
];
