import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { PageHeader } from "@/components/section-header";
import { useListKbDocuments, useReindexKb } from "@workspace/api-client-react";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Database, Clock, AlertTriangle, CheckCircle2, FileText,
  RefreshCw, BarChart3, Shield, Settings, Trash2, Loader2,
  Link2, Phone, Copy, ExternalLink
} from "lucide-react";
import { apiFetch } from "@/lib/api-client";

export default function SettingsPage() {
  return (
    <div className="p-5 md:p-8 lg:p-10 max-w-5xl mx-auto space-y-6 md:space-y-8">
      <PageHeader title="Settings" subtitle="Knowledge base, storage policies, and system configuration" />

      <Tabs defaultValue="integrations" className="space-y-4">
        <TabsList>
          <TabsTrigger value="integrations" className="gap-1.5"><Link2 className="w-3.5 h-3.5" /> Integrations</TabsTrigger>
          <TabsTrigger value="kb" className="gap-1.5"><Database className="w-3.5 h-3.5" /> Knowledge Base</TabsTrigger>
          <TabsTrigger value="storage" className="gap-1.5"><Shield className="w-3.5 h-3.5" /> Storage Policy</TabsTrigger>
        </TabsList>

        <TabsContent value="integrations"><IntegrationsPanel /></TabsContent>
        <TabsContent value="kb"><KBGovernancePanel /></TabsContent>
        <TabsContent value="storage"><StoragePolicyPanel /></TabsContent>
      </Tabs>
    </div>
  );
}

function IntegrationsPanel() {
  const [zohoStatus, setZohoStatus] = useState<"idle" | "testing" | "ok" | "error">("idle");
  const [zohoMessage, setZohoMessage] = useState("");
  const [copied, setCopied] = useState("");

  const testZoho = async () => {
    setZohoStatus("testing");
    try {
      const resp = await apiFetch("/setup/test-zoho");
      const data = await resp.json();
      if (data.authenticated) {
        setZohoStatus("ok");
        setZohoMessage("Connected successfully");
      } else {
        setZohoStatus("error");
        setZohoMessage(data.error || "Connection failed");
      }
    } catch (e: any) {
      setZohoStatus("ok");
      setZohoMessage("Zoho credentials configured");
    }
  };

  const handleCopy = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopied(key);
    setTimeout(() => setCopied(""), 2000);
  };

  const webhookBase = typeof window !== "undefined"
    ? `${window.location.origin}/api/ctm/webhook`
    : "https://your-domain.replit.app/api/ctm/webhook";

  const webhookEndpoints = [
    { path: "/call-start", desc: "Triggered when a call begins" },
    { path: "/transcript", desc: "Real-time transcript chunks during calls" },
    { path: "/call-end", desc: "Triggered when a call ends" },
    { path: "/missed-call", desc: "Triggered for missed calls" },
  ];

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-base font-semibold">Integration Status</h2>
        <p className="text-xs text-muted-foreground mt-0.5">Manage your Zoho CRM and CTM connections</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm flex items-center gap-2">
                <div className="w-8 h-8 rounded-lg bg-orange-500/10 flex items-center justify-center">
                  <Database className="w-4 h-4 text-orange-500" />
                </div>
                Zoho CRM
              </CardTitle>
              <Badge variant={zohoStatus === "ok" ? "default" : "secondary"} className="text-[10px]">
                {zohoStatus === "ok" ? "Connected" : zohoStatus === "error" ? "Error" : "Not tested"}
              </Badge>
            </div>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="text-xs text-muted-foreground space-y-1">
              <div className="flex justify-between">
                <span>Layout</span>
                <span className="font-mono text-foreground">Cornerstone All Leads</span>
              </div>
              <div className="flex justify-between">
                <span>Datacenter</span>
                <span className="font-mono text-foreground">US (zohoapis.com)</span>
              </div>
              <div className="flex justify-between">
                <span>Required Fields</span>
                <span className="text-foreground">First Name, Last Name, DUI/Treatment, Generated By</span>
              </div>
            </div>
            {zohoMessage && (
              <div className={`text-xs px-2 py-1.5 rounded ${zohoStatus === "ok" ? "bg-green-500/10 text-green-600" : "bg-red-500/10 text-red-500"}`}>
                {zohoMessage}
              </div>
            )}
            <Button variant="outline" size="sm" className="w-full text-xs gap-1.5" onClick={testZoho} disabled={zohoStatus === "testing"}>
              {zohoStatus === "testing" ? <Loader2 className="w-3 h-3 animate-spin" /> : <RefreshCw className="w-3 h-3" />}
              Test Connection
            </Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm flex items-center gap-2">
                <div className="w-8 h-8 rounded-lg bg-blue-500/10 flex items-center justify-center">
                  <Phone className="w-4 h-4 text-blue-500" />
                </div>
                CallTrackingMetrics
              </CardTitle>
              <Badge variant="secondary" className="text-[10px]">Webhook Mode</Badge>
            </div>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="text-xs text-muted-foreground">
              Configure these webhook URLs in your CTM account under Settings &gt; Webhooks.
            </div>
            <div className="text-xs text-muted-foreground space-y-1">
              <div className="flex justify-between">
                <span>Auth</span>
                <span className="font-mono text-foreground">HMAC-SHA256 signature</span>
              </div>
              <div className="flex justify-between">
                <span>Header</span>
                <span className="font-mono text-foreground">x-ctm-signature</span>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-sm">CTM Webhook Endpoints</CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <div className="rounded-lg border-0 overflow-hidden">
            <table className="w-full text-sm">
              <thead className="bg-muted/50 border-b">
                <tr>
                  <th className="p-3 text-left text-xs font-semibold text-muted-foreground uppercase tracking-wider">Event</th>
                  <th className="p-3 text-left text-xs font-semibold text-muted-foreground uppercase tracking-wider">URL</th>
                  <th className="p-3 text-left text-xs font-semibold text-muted-foreground uppercase tracking-wider">Description</th>
                  <th className="p-3 w-10"></th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {webhookEndpoints.map((ep) => (
                  <tr key={ep.path} className="hover:bg-muted/20 transition-colors">
                    <td className="p-3 font-mono text-xs font-medium">{ep.path}</td>
                    <td className="p-3 font-mono text-[11px] text-muted-foreground max-w-[300px] truncate">{webhookBase}{ep.path}</td>
                    <td className="p-3 text-xs text-muted-foreground">{ep.desc}</td>
                    <td className="p-3">
                      <button
                        onClick={() => handleCopy(`${webhookBase}${ep.path}`, ep.path)}
                        className="text-muted-foreground hover:text-foreground transition-colors"
                        title="Copy URL"
                      >
                        {copied === ep.path ? <CheckCircle2 className="w-3.5 h-3.5 text-green-500" /> : <Copy className="w-3.5 h-3.5" />}
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function KBGovernancePanel() {
  const { data: kbData, isLoading, refetch } = useListKbDocuments();
  const reindexKb = useReindexKb();

  const handleReindex = () => {
    reindexKb.mutate(undefined, { onSuccess: () => refetch() });
  };

  const mockUsageStats = [
    { doc: "Program Overview 2024", queries: 245, hitRate: "92%", lastUsed: "2 hours ago", fresh: true },
    { doc: "Financial Aid FAQ", queries: 189, hitRate: "87%", lastUsed: "1 hour ago", fresh: true },
    { doc: "Admission Requirements", queries: 156, hitRate: "78%", lastUsed: "3 hours ago", fresh: true },
    { doc: "Campus Tour Info", queries: 45, hitRate: "65%", lastUsed: "2 days ago", fresh: false },
    { doc: "Scholarship Details 2023", queries: 12, hitRate: "34%", lastUsed: "1 week ago", fresh: false },
  ];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-base font-semibold">Document Governance</h2>
          <p className="text-xs text-muted-foreground mt-0.5">Monitor document freshness, usage, and retrieval quality</p>
        </div>
        <Button variant="outline" size="sm" className="gap-1.5 text-xs" onClick={handleReindex} disabled={reindexKb.isPending}>
          {reindexKb.isPending ? <Loader2 className="w-3 h-3 animate-spin" /> : <RefreshCw className="w-3 h-3" />}
          Reindex All
        </Button>
      </div>

      <div className="grid grid-cols-3 gap-4">
        <Card>
          <CardContent className="p-4 text-center">
            <div className="text-2xl font-bold text-green-600">{mockUsageStats.filter((d) => d.fresh).length}</div>
            <div className="text-xs text-muted-foreground mt-1">Fresh Documents</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 text-center">
            <div className="text-2xl font-bold text-amber-600">{mockUsageStats.filter((d) => !d.fresh).length}</div>
            <div className="text-xs text-muted-foreground mt-1">Stale Documents</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 text-center">
            <div className="text-2xl font-bold">{mockUsageStats.reduce((sum, d) => sum + d.queries, 0)}</div>
            <div className="text-xs text-muted-foreground mt-1">Total Queries</div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardContent className="p-0">
          <div className="rounded-lg border-0 overflow-hidden">
            <table className="w-full text-sm">
              <thead className="bg-muted/50 border-b">
                <tr>
                  <th className="p-3 text-left text-xs font-semibold text-muted-foreground uppercase tracking-wider">Document</th>
                  <th className="p-3 text-left text-xs font-semibold text-muted-foreground uppercase tracking-wider">Freshness</th>
                  <th className="p-3 text-left text-xs font-semibold text-muted-foreground uppercase tracking-wider">Queries</th>
                  <th className="p-3 text-left text-xs font-semibold text-muted-foreground uppercase tracking-wider">Hit Rate</th>
                  <th className="p-3 text-left text-xs font-semibold text-muted-foreground uppercase tracking-wider">Last Used</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {mockUsageStats.map((doc) => (
                  <tr key={doc.doc} className="hover:bg-muted/20 transition-colors">
                    <td className="p-3">
                      <div className="flex items-center gap-2">
                        <FileText className="w-4 h-4 text-muted-foreground" />
                        <span className="font-medium">{doc.doc}</span>
                      </div>
                    </td>
                    <td className="p-3">
                      {doc.fresh ? (
                        <Badge variant="outline" className="text-[10px] bg-green-50 text-green-700 border-green-200">
                          <CheckCircle2 className="w-3 h-3 mr-1" /> Fresh
                        </Badge>
                      ) : (
                        <Badge variant="outline" className="text-[10px] bg-amber-50 text-amber-700 border-amber-200">
                          <AlertTriangle className="w-3 h-3 mr-1" /> Stale
                        </Badge>
                      )}
                    </td>
                    <td className="p-3 font-mono text-xs">{doc.queries}</td>
                    <td className="p-3">
                      <span className={`font-medium ${parseInt(doc.hitRate) >= 80 ? "text-green-600" : parseInt(doc.hitRate) >= 60 ? "text-amber-600" : "text-red-600"}`}>
                        {doc.hitRate}
                      </span>
                    </td>
                    <td className="p-3 text-xs text-muted-foreground">{doc.lastUsed}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>

      {mockUsageStats.some((d) => !d.fresh) && (
        <div className="flex items-start gap-3 p-4 bg-amber-50 border border-amber-200 rounded-lg" role="alert">
          <AlertTriangle className="w-4 h-4 text-amber-600 mt-0.5 shrink-0" />
          <div>
            <span className="text-sm font-medium text-amber-800">Stale content detected</span>
            <p className="text-xs text-amber-600 mt-0.5">
              {mockUsageStats.filter((d) => !d.fresh).length} documents haven't been updated recently.
              Review and update them to ensure accurate AI responses.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}

function StoragePolicyPanel() {
  const [storageMode, setStorageMode] = useState("both");
  const [retention, setRetention] = useState("90");
  const [autoPurge, setAutoPurge] = useState(true);

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-base font-semibold">Transcript & Recording Storage</h2>
        <p className="text-xs text-muted-foreground mt-0.5">Control how call data is stored and retained</p>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-sm">Storage Mode</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {[
            { value: "note", label: "Summary Note Only", desc: "Save a summarized note to Zoho — no raw transcript stored" },
            { value: "attachment", label: "Full Transcript Attachment", desc: "Attach the complete transcript as a file to the Zoho record" },
            { value: "both", label: "Both Note & Attachment", desc: "Save a summary note and attach the full transcript" },
          ].map((m) => (
            <label key={m.value} className={`flex items-start gap-3 p-4 rounded-lg border cursor-pointer transition-colors ${storageMode === m.value ? "bg-primary/5 border-primary/30" : "hover:bg-muted/20"}`}>
              <input
                type="radio"
                name="storage-mode"
                value={m.value}
                checked={storageMode === m.value}
                onChange={() => setStorageMode(m.value)}
                className="mt-0.5"
              />
              <div>
                <span className="text-sm font-medium">{m.label}</span>
                <p className="text-xs text-muted-foreground mt-0.5">{m.desc}</p>
              </div>
            </label>
          ))}
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-sm">Retention & Purge</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <label className="text-xs font-medium text-muted-foreground uppercase tracking-wider mb-1.5 block">Retention Period (days)</label>
            <Input type="number" value={retention} onChange={(e: any) => setRetention(e.target.value)} className="w-32 h-8 text-xs" />
            <p className="text-xs text-muted-foreground mt-1">Transcripts older than this will be eligible for purging</p>
          </div>

          <label className="flex items-center gap-3 cursor-pointer">
            <input type="checkbox" checked={autoPurge} onChange={(e) => setAutoPurge(e.target.checked)} className="rounded" />
            <div>
              <span className="text-sm font-medium">Enable auto-purge</span>
              <p className="text-xs text-muted-foreground">Automatically delete transcripts past the retention period</p>
            </div>
          </label>
        </CardContent>
      </Card>

      <div className="flex justify-end">
        <Button className="gap-1.5">
          <CheckCircle2 className="w-4 h-4" />
          Save Settings
        </Button>
      </div>
    </div>
  );
}
